### ISSUE TITLE
Still alive?

### ISSUE THREAD

**Issue by Ed1123** [CedricFR/dataenforce#15]
Was wondering if this project is still alive. I was considering including it in my projects.

**Comment by Codyk12** [comment]
@CedricFR ^?

**Comment by CedricFR** [comment]
I am not maintaining this project any more and have no concrete development plan for it. If someone would like to take over & bring it to the next level I'm happy to facilitate the transition.

Alternatively, I recommend using [pandera](https://github.com/unionai-oss/pandera) which provides a similar functionality (& much more!)
