### ISSUE TITLE
Extending the functionality to Series?

### ISSUE THREAD

**Issue by fkromer** [CedricFR/dataenforce#3]
I join in... cool project. Are you planning to extend the functionality to [pandas.Series](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.Series.html) (type of index, type of data)?

**Comment by CedricFR** [comment]
This feature is not planned at the moment, but if you come up with a good implementation I'd be happy to include!

**Comment by fkromer** [comment]
@CedricFR Thanks for letting me know. I'll probably stick to a private "just good enough" solution for now 😏 In case I'll PR and reopen the issue in the future.
