### ISSUE TITLE
PyRe check, Undefined or invalid type [11]: Annotation is not defined as a type.

### ISSUE THREAD

**Issue by sinaiy** [CedricFR/dataenforce#8]
when using PyRe check, i get the following 
`Undefined or invalid type [11]: Annotation `DummyDataframe` is not defined as a type.`

code example
```
from dataenforce import Dataset

DummyDataframe = Dataset["id": int]


def test_annotation(_df: DummyDataframe) -> DummyDataframe:
    pass
```

is there something that can be done to avoid/fix this issue?

**Comment by CedricFR** [comment]
Hi @sinaiy,

I don't use PyRe so my answer may be off, have you tried this? https://www.python.org/dev/peps/pep-0613/

It mentions at the bottom that PyRe supports type alias, though I can't find any other mention elsewhere.

Let us know how that goes
/C

**Comment by sinaiy** [comment]
thanks,
this looks promising, but it appears as if TypeAlias is only supported in python 3.10.
