### ISSUE TITLE
Unable to type-cast a dataframe to Dataset

### ISSUE THREAD

**Issue by anton164** [CedricFR/dataenforce#9]
```python
from typing import cast       

df = cast(Dataset["timestamp", "volume"], df)
```

Gives the error:
```
Expected class type but received "Unknown | DatasetMeta"
  "DatasetMeta" is not a classPylancereportGeneralTypeIssues
```

Is this an issue with Pylance? I would expect to be able to cast a dataframe to the Dataset type

**Comment by anton164** [comment]
The same happens when I define it as the return type of a method 🤔 :
![Screen Shot 2021-07-01 at 10 57 55 AM](https://user-images.githubusercontent.com/1349225/124145965-4934ac80-da5b-11eb-94f4-a7f66bb90dc4.png)

**Comment by CedricFR** [comment]
I am not using Pylance so I don't really know why it doesn't accept it. Maybe it is a special case that it doesn't support.
See e.g. https://github.com/microsoft/pylance-release/issues/360 which looks similar.

Cheers
/C
